# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mappable_object_attributes"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Nguyen"]
  s.date = "2013-08-12"
  s.description = "Using the power of Hashie::Mash to define how a record consumes external data into defined records."
  s.email = "dansonguyen@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/mappable_object_attributes.rb",
    "lib/mappable_object_attributes/data_attributes_map.rb",
    "lib/mappable_object_attributes/mappable_data.rb",
    "spec/integration/with_active_record_spec.rb",
    "spec/mappable_object_attributes_spec.rb",
    "spec/spec_helper.rb",
    "spec/spec_helper_with_ar.rb",
    "spec/unit/data_attributes_map_spec.rb",
    "spec/unit/deprecated_spec.rb",
    "spec/unit/mappable_object_spec.rb"
  ]
  s.homepage = "http://github.com/dannguyen/mappable_object_attributes"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.5"
  s.summary = "A convenience wrapper to help with defining how a record is created"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_runtime_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<database_cleaner>, ["= 1.0.1"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<activesupport>, [">= 3.2.14"])
      s.add_development_dependency(%q<activerecord>, [">= 3.2.14"])
      s.add_development_dependency(%q<protected_attributes>, [">= 0"])
    else
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<database_cleaner>, ["= 1.0.1"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<activesupport>, [">= 3.2.14"])
      s.add_dependency(%q<activerecord>, [">= 3.2.14"])
      s.add_dependency(%q<protected_attributes>, [">= 0"])
    end
  else
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.14.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<database_cleaner>, ["= 1.0.1"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<activesupport>, [">= 3.2.14"])
    s.add_dependency(%q<activerecord>, [">= 3.2.14"])
    s.add_dependency(%q<protected_attributes>, [">= 0"])
  end
end

